### ISSUE TITLE
batchsize

### ISSUE THREAD

**Issue by jialeren** [sahithchada/NOCS_PyTorch#2]
During training, is it only possible to support a batchsize of 1?

**Comment by bharathsivaram10** [comment]
Essentially, your batch size  = GPU_COUNT * IMAGES_PER_GPU (lines 53 and 54 of train.py).
Assuming you're training on a single GPU, you should be able to change the IMAGES_PER_GPU to the batch size you want.
See if that works.

**Comment by jialeren** [comment]
When I change IMAGES_PER_GPU,  errors will be reported when running train.py. When using different batch sizes, the error reports are also different.

I checked the code and found that there is a comment `#Currently only supports batchsize 1 `(line 467 of model.py). 

And I noticed that this is because the dimensions of `_gt_class_ids, gt_boxes_ `and other values ​​in the dataset are not unified. They depend on the number of objects in the picture, which varies from image to image.

**Comment by bharathsivaram10** [comment]
Thanks for your patience. I have a vague recollection of doing batch size of two at some point, so something must have changed which is why we have that comment. While we look into this, I'd recommend two things:

1) There may be some way to add zero-padding such that batch_size > 1 works
2) Try looking at the original [tf implementation](https://github.com/hughw19/NOCS_CVPR2019/tree/master) since ours is essentially modeled off that and they originally have batch size 2

**Comment by bharathsivaram10** [comment]
Closed due to inactivity
